<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" 
 	xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    	xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    	xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	name="mybot_xacro">

	<!-- KINECT ATTACHMENT -->
	<xacro:include filename="$(find diff_decription)/urdf/sensors/kinect.xacro"/>
	<kinect_sensor parent="kinect_base_link">
		<!--origin xyz="0 0 0" rpy="0 0 0" /-->
	</kinect_sensor>
	
	<!-- LASER ATTACHMENT -->
	<xacro:include filename="$(find diff_decription)/urdf/sensors/hokuyo.xacro"/>
	<hokuyo_sensor parent="upper_base_link">
		<!--origin xyz="0 0 0" rpy="0 0 0" /-->
	</hokuyo_sensor>
	
	<!-- Import all Gazebo-customization elements, including Gazebo colors, sensors, controller -->
  	<xacro:include filename="$(find diff_decription)/urdf/robot_model_gazebo.gazebo" />
	
	<!-- Add view camera - working -->
	<xacro:include filename="$(find rdiff_decription)/urdf/sensors/view_camera.xacro" />
	<view_camera_sensor parent="kinect_base_link">
		<!--origin xyz="0 0 0" rpy="0 0 0" /-->
	</view_camera_sensor>	
	
	
	<xacro:property name="length_wheel" value="0.075" />
	<xacro:property name="radius_wheel" value="0.0775" />
	<xacro:property name="mass_wheel" value="2" />
	<xacro:property name="distance_2wheels" value="0.39" />	

	<xacro:property name="radius_base" value="0.225" />
	<xacro:property name="length_base" value="0.025" />
	<xacro:property name="mass_base" value="10" />
	
	<xacro:property name="height_cpu" value="0.095" />
	<!--xacro:property name="height_torso" value="0.625" /-->
	<xacro:property name="height_torso" value="0.725" />
	<xacro:property name="height_side_torso" value="0.775" />
	<xacro:property name="height_head_pan" value="0.06" />
	<xacro:property name="height_head_tilt" value="0.045" />
		

	<xacro:macro name="default_inertial" params="mass">
               <inertial>
                       <mass value="${mass}" />
                       <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                                iyy="1.0" iyz="0.0"
                                izz="1.0" />
               </inertial>
	</xacro:macro>
	
	<xacro:macro name="cylinder_inertia" params="m r h">
		<inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
	    		iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
	    		izz="${m*r*r/2}"
  		/>
	</xacro:macro>	

	<xacro:macro name="sphere_inertia" params="m r">
		<inertia
			ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
		    	iyy="${2*m*r*r/5}" iyz = "0"
		    	izz="${2*m*r*r/5}"
		/>
	</xacro:macro>

	<link name="base_footprint">
   		<visual>
			<geometry>
      				<box size="0.001 0.001 0.001"/>
     			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<!--origin rpy="0 0 -0.784900" xyz="0 0 0"/-->
   		</visual>
		<xacro:default_inertial mass="0.0001"/>
 	</link>

	<gazebo reference="base_footprint">
		<material>Gazebo/Green</material>
		<turnGravityOff>false</turnGravityOff>
	</gazebo>

	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 0" />
		<parent link="base_footprint" />
		<child link="base_link" />
	</joint>

	<link name="base_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<cylinder radius="${radius_base}" length="${length_base}"/>
			</geometry>
			<material name="Orange">
				<color rgba="1.0 0.4 0.0 1.0"/>
			</material>
		</visual>
		<collision>
			<geometry>
       				<cylinder radius="${radius_base}" length="${length_base}"/>
			</geometry>
		</collision>
		<inertial>
		    <mass value="${mass_base}"/>
		    <cylinder_inertia m="45" r="${radius_base}" h="${length_base}"/>
	  	</inertial>
	</link>
	<!--front wheel -->	
	<link name="wheel_1">
	  
		  <visual>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <geometry>
		      <sphere radius="${radius_wheel/2}"/>
		    </geometry>
		    <material name="black">
			<color rgba="0 0 0 1"/>
		    </material>
		  </visual>
		
  		  <collision>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <geometry>
		      <sphere radius="${radius_wheel/2}"/>
		    </geometry>
		  </collision>

		  <inertial>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <mass value="${mass_wheel}"/>
		    <sphere_inertia m="${mass_wheel}" r="${radius_wheel/2}"/>
		  </inertial>
	</link>
	<!-- left wheel -->
 	<link name="wheel_2">
   		<visual>
     			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
     			</geometry>
			<!-- <origin rpy="0 1.5 0" xyz="-0.1 0.1 0"/> -->
			<origin rpy="0 0 0" xyz="0 0 0"/>
   			<material name="black"/>
   		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
			</geometry>
		</collision>
		<inertial>
		    <mass value="${mass_wheel}"/>
		    <cylinder_inertia m="${mass_wheel}" r="${radius_wheel}" h="${length_wheel}"/>
	  	</inertial>

 	</link>
    	<!-- back wheel -->
	<link name="wheel_3">
	  
		  <visual>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <geometry>
		      <sphere radius="${radius_wheel/2}"/>
		    </geometry>
		    <material name="black">
			<color rgba="0 0 0 1"/>
		    </material>
		  </visual>
		
  		  <collision>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <geometry>
		      <sphere radius="${radius_wheel/2}"/>
		    </geometry>
		  </collision>

		  <inertial>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <mass value="${mass_wheel}"/>
		    <sphere_inertia m="${mass_wheel}" r="${radius_wheel/2}"/>
		  </inertial>
	</link>
	<!-- right wheel -->
 	<link name="wheel_4">
   		<visual>
     			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
     			</geometry>
		<!--	<origin rpy="0 1.5 0" xyz="-0.1 -0.1 0"/> -->
			<origin rpy="0 0 0" xyz="0 0 0" />
   			<material name="black"/>
   		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0" />			
			<geometry>
       				<cylinder length="${length_wheel}" radius="${radius_wheel}"/>
			</geometry>
		</collision>
		<inertial>
		
		    <mass value="${mass_wheel}"/>
		    <cylinder_inertia m="${mass_wheel}" r="${radius_wheel}" h="${length_wheel}"/>
	  	</inertial>


 	</link>

	<link name="cpu_link">
   		<visual>
			<geometry>
      				<box size="0.35 .19 ${height_cpu}"/>
     			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${height_cpu/2}"/>
			<material name="Cyan2">
				<color rgba="0 0.7 0.7 1.0"/>
			</material>
   		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 ${height_cpu/2}"/>
			<geometry>
       				<box size="0.35 .19 ${height_cpu}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="2"/>
 	</link>

	<link name="upper_base_link">
		<visual>
			<origin xyz="0 0 ${length_base/2}" rpy="0 0 0"/>
			<geometry>
				<cylinder radius="${radius_base}" length="${length_base}"/>
			</geometry>
			<material name="Orange">
				<color rgba="1.0 0.4 0.0 1.0"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 ${length_base/2}" rpy="0 0 0"/>
			<geometry>
       				<cylinder radius="${radius_base}" length="${length_base}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>
	</link>

	<link name="torso_link">
		<visual>
			<origin xyz="0 0 ${height_torso/2}" rpy="0 0 0"/>
			<geometry>
				<box size="0.05 0.1 ${height_torso}"/>
			</geometry>
			<material name="Yellow2">
				<color rgba="0.8 0.8 0 1.0"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 ${height_torso/2}" rpy="0 0 0"/>			
			<geometry>
       				<box size="0.05 0.1 ${height_torso}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>
	</link>

	<link name="right_torso_link">
		<visual>
			<origin xyz="0 0 ${height_torso/2}" rpy="0 0 0"/>
			<geometry>
				<box size="0.05 0.025 ${height_torso}"/>
			</geometry>
			<material name="Grey2">
				<color rgba="0.6 0.6 0.6 1.0"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 ${height_torso/2}" rpy="0 0 0"/>			
			<geometry>
       				<box size="0.05 0.1 ${height_torso}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>
	</link>

	<link name="left_torso_link">
		<visual>
			<origin xyz="0 0 ${height_torso/2}" rpy="0 0 0"/>
			<geometry>
				<box size="0.05 0.025 ${height_torso}"/>
			</geometry>
			<material name="Grey2">
				<color rgba="0.6 0.6 0.6 1.0"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 ${height_torso/2}" rpy="0 0 0"/>			
			<geometry>
       				<box size="0.05 0.1 ${height_torso}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>
	</link>

	<link name="top_torso_link">
		<visual>
			<origin xyz="0 0 ${length_base/2}" rpy="0 0 0"/>
			<geometry>
				<box size="0.05 0.175 ${length_base}"/>
			</geometry>
			<material name="Grey2">
				<color rgba="0.6 0.6 0.6 1.0"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 ${length_base/2}" rpy="0 0 0"/>
			<geometry>
       				<box size="0.05 0.125 ${length_base}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="0.125"/>
	</link>
	
	<link name="head_pan_link">
		<visual>
			<origin xyz="0 0 ${height_head_pan/2}" rpy="0 0 0"/>
			<geometry>
				<box size="0.05 0.045 ${height_head_pan}"/>
			</geometry>
			<material name="Green1">
				<color rgba="0 1 0 1.0"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 ${height_head_pan/2}" rpy="0 0 0"/>
			<geometry>
       				<box size="0.05 0.045 ${height_head_pan}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="0.125"/>
	</link>
	
	<link name="head_tilt_link">
		<visual>
			<origin xyz="0 0 ${height_head_tilt/2}" rpy="0 0 0"/>
			<geometry>
				<box size="0.03 0.038 ${height_head_tilt}"/>
			</geometry>
			<material name="Green1">
				<color rgba="0 1 0 1.0"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 ${height_head_tilt/2}" rpy="0 0 0"/>
			<geometry>
       				<box size="0.03 0.038 ${height_head_tilt}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="0.125"/>
	</link>

	<link name="kinect_base_link">
		<visual>
			<origin xyz="0 0 ${length_base/2}" rpy="0 0 0"/>
			<geometry>
				<box size="0.06 0.065 ${length_base}"/>
			</geometry>
			<material name="Green3">
				<color rgba="0.1 0.5 0.1 1.0"/>
			</material>
		</visual>
		<collision>
			<geometry>
       				<box size="0.06 0.065 ${length_base}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="0.125"/>
	</link>

	<link name="screen_link">
		<visual>
			<origin xyz="0.06 0 -0.11" rpy="0 -0.5 0"/>
			<geometry>
				<box size="0.01 0.3 0.16"/>
			</geometry>
		<material name="Grey3">
			<color rgba="0.2 0.2 0.2 1.0"/>
		</material>
		</visual>
		<collision>
			<origin xyz="0.06 0 -0.11" rpy="0 -0.5 0"/>
			<geometry>
       				<box size="0.01 0.3 0.16"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="0.125"/>
	</link>

<!-- -->
 <joint name="base_to_wheel1" type="fixed">
   <parent link="base_link"/>
   <child link="wheel_1"/>
   <!--added length_base/32 to get the contact of the wheel with the floor -->
   <origin rpy="0 0 0" xyz="0.18 0 ${-radius_wheel/2+length_base/256}"/>
   <axis xyz="0 0 1" />
 </joint>

 <joint name="base_to_wheel2" type="continuous">
   <axis xyz="0 0 1" />
   <anchor xyz="0 0 0" />
   <limit effort="100" velocity="100" />
   <parent link="base_link"/>
   <child link="wheel_2"/>
   <origin rpy="-1.5707 0 0" xyz="0 -0.195 0"/>
</joint>
<!-- -->
 <joint name="base_to_wheel3" type="fixed">
   <parent link="base_link"/>
   <axis xyz="0 0 1" />
   <child link="wheel_3"/>
   <!--added length_base/32 to get the contact of the wheel with the floor -->
   <origin rpy="0 0 0" xyz="-0.18 0 ${-radius_wheel/2+length_base/256}"/> 
 </joint>

 <joint name="base_to_wheel4" type="continuous">
   <parent link="base_link"/>
   <axis xyz="0 0 1" />
   <child link="wheel_4"/>
   <origin rpy="-1.5707 0 0" xyz="0 0.195 0"/>
 </joint>

 	<joint name="cpu_base_joint" type="fixed">
		<origin xyz="0 0 0" />
		<parent link="base_link" />
		<child link="cpu_link" />
	</joint>

 	<joint name="upper_base_cpu_joint" type="fixed">
		<origin xyz="0 0 ${height_cpu}" />
		<parent link="cpu_link" />
		<child link="upper_base_link" />
	</joint>

 	<joint name="torso_upper_base_joint" type="fixed">
		<origin xyz="0 0 ${length_base}" />
		<parent link="upper_base_link" />
		<child link="torso_link" />
	</joint>


	<joint name="right_torso_upper_base_joint" type="fixed">
		<origin xyz="0 -0.075 ${length_base}" />
		<parent link="upper_base_link"/>
		<child link="right_torso_link"/>
	</joint>

	<joint name="left_torso_upper_base_joint" type="fixed">
		<parent link="upper_base_link"/>
		<child link="left_torso_link"/>
		<origin xyz="0 0.075 ${length_base}" />
	</joint>

	<joint name="top_torso_torso_joint" type="fixed">
		<parent link="torso_link"/>
		<child link="top_torso_link"/>
		<origin xyz="0 0 ${height_torso}" />
	</joint>

	<joint name="head_pan_servo" type="fixed">
		<parent link="top_torso_link"/>
		<child link="head_pan_link"/>
		<origin xyz="0 0 ${length_base}" rpy="0 0 0"/>
	</joint>

	<joint name="head_pan_joint" type="fixed">
		<parent link="head_pan_link"/>
		<child link="head_tilt_link"/>
		<origin xyz="0 0 ${height_head_pan}" rpy="0 0 0"/>
	
	</joint>

	<joint name="kinect_base_joint" type="fixed">
		<parent link="head_tilt_link"/>
		<child link="kinect_base_link"/>
		<origin xyz="0 0 ${height_head_tilt}" rpy="0 0 0"/>
	
	</joint>

	<joint name="screen_joint" type="fixed">
		<parent link="top_torso_link"/>
		<child link="screen_link"/>
		<origin xyz="0 0 0.025" rpy="0 0 0"/>
	</joint>


</robot>
